
## YAML
# 實驗基本資訊
experiment_name: "robot_axis1_current_analysis"

# data paths
data:
  raw_path: "../data/raw/RMBR4-2_export_test.csv"
  processed_path: "../data/processed/cleaned_data.csv"

# Model training parameters
model_params:
  learning_rate: 0.01
  iterations: 1500
  window_size: 500 # ==> by Hyperparameter Sweep

# Predictive maintenance and alarm settings
maintenance:
  failure_threshold: 1.0   # A current of XXX is defined as a failure.
  alert_buffer_days: 14    # An alert is issued XX days in advance.

# Neon connection settings
database:
  enabled: true  # switch：true or false
  db_url: "postgresql://neondb_owner:npg_AelL3bdJj8Tt@ep-icy-sound-aiqbpzyi-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
  table_name: "robot_telemetry"